// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Js_mapperRt from "bs-platform/lib/es6/js_mapperRt.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as ReactKawaii from "react-kawaii";

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -326580162,
    "lovestruck"
  ],
  /* tuple */[
    -293737407,
    "shocked"
  ],
  /* tuple */[
    -281233442,
    "blissful"
  ],
  /* tuple */[
    23972,
    "ko"
  ],
  /* tuple */[
    5740566,
    "sad"
  ],
  /* tuple */[
    572482848,
    "happy"
  ],
  /* tuple */[
    691427738,
    "excited"
  ]
];

function moodToJs(param) {
  return Js_mapperRt.binarySearch(7, param, jsMapperConstantArray);
}

function moodFromJs(param) {
  return Js_mapperRt.revSearch(7, jsMapperConstantArray, param);
}

function make(mood, size, color, children) {
  var tmp = { };
  var tmp$1 = Belt_Option.map(mood, moodToJs);
  if (tmp$1 !== undefined) {
    tmp.mood = Caml_option.valFromOption(tmp$1);
  }
  if (size !== undefined) {
    tmp.size = Caml_option.valFromOption(size);
  }
  if (color !== undefined) {
    tmp.color = Caml_option.valFromOption(color);
  }
  return ReasonReact.wrapJsForReason(ReactKawaii.Backpack, tmp, children);
}

export {
  moodToJs ,
  moodFromJs ,
  make ,
  
}
/* ReasonReact Not a pure module */
