// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as ReactKawaii from "react-kawaii";

function make(mood, size, color, children) {
  var tmp = { };
  if (mood !== undefined) {
    tmp.mood = Caml_option.valFromOption(mood);
  }
  if (size !== undefined) {
    tmp.size = Caml_option.valFromOption(size);
  }
  if (color !== undefined) {
    tmp.color = Caml_option.valFromOption(color);
  }
  return ReasonReact.wrapJsForReason(ReactKawaii.Backpack, tmp, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
