// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as TwemojiMini from "./twemoji-mini";

var base = "https://twemoji.maxcdn.com/2/";

function grabTheRightIcon(prim) {
  return TwemojiMini.grabTheRightIcon(prim);
}

function emojiUrl(echar) {
  return base + ("svg/" + (TwemojiMini.grabTheRightIcon(echar) + ".svg"));
}

export {
  base ,
  grabTheRightIcon ,
  emojiUrl ,
  
}
/* ./twemoji-mini Not a pure module */
