// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Kawaii$ReasonreactExamples from "../bindings/Kawaii.bs.js";
import * as Prelude$ReasonreactExamples from "../Prelude.bs.js";

var component = Curry._1(Prelude$ReasonreactExamples.RR[/* statelessComponent */0], "Component2-ReasonreactExamples");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "KawaiiDemo"
                        }, React.createElement("h1", undefined, Prelude$ReasonreactExamples.s("React-Kawaii Demo")), ReasonReact.element(undefined, undefined, Kawaii$ReasonreactExamples.make(/* happy */572482848, undefined, undefined, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
