// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Prelude$ReasonreactExamples from "../Prelude.bs.js";
import * as CoolContainer$ReasonreactExamples from "../components/CoolContainer.bs.js";

var component = Curry._1(Prelude$ReasonreactExamples.RR[/* statelessComponent */0], "ContainerDemo-ReasonreactExamples");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("h1", undefined, Prelude$ReasonreactExamples.s("Container")), ReasonReact.element(undefined, undefined, CoolContainer$ReasonreactExamples.make(/* array */[Prelude$ReasonreactExamples.s("This is a container")])), ReasonReact.element(undefined, undefined, CoolContainer$ReasonreactExamples.make(/* array */[
                                  React.createElement("p", undefined, Prelude$ReasonreactExamples.s("This container has more content")),
                                  React.createElement("p", undefined, Prelude$ReasonreactExamples.s("这个容器的内容更丰富一些"))
                                ])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
