// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Js_mapperRt from "bs-platform/lib/es6/js_mapperRt.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Kawaii$ReasonreactExamples from "../bindings/Kawaii.bs.js";
import * as Select$ReasonreactExamples from "../components/Select.bs.js";
import * as Prelude$ReasonreactExamples from "../Prelude.bs.js";

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -826612882,
    "SpeechBubble"
  ],
  /* tuple */[
    -331020616,
    "Planet"
  ],
  /* tuple */[
    -64353120,
    "Backpack"
  ],
  /* tuple */[
    3855327,
    "Mug"
  ],
  /* tuple */[
    80675545,
    "CreditCart"
  ],
  /* tuple */[
    633016855,
    "IceCream"
  ],
  /* tuple */[
    646315823,
    "Ghost"
  ]
];

function compChoiceToJs(param) {
  return Js_mapperRt.binarySearch(7, param, jsMapperConstantArray);
}

function compChoiceFromJs(param) {
  return Js_mapperRt.revSearch(7, jsMapperConstantArray, param);
}

var include = Select$ReasonreactExamples.Make(/* module */[]);

var make = include[1];

var compItems = Belt_Array.map(/* array */[
      /* Backpack */-64353120,
      /* CreditCart */80675545,
      /* Ghost */646315823,
      /* IceCream */633016855,
      /* Mug */3855327,
      /* Planet */-331020616,
      /* SpeechBubble */-826612882
    ], (function (comp) {
        return /* record */[
                /* label */compChoiceToJs(comp),
                /* value */comp
              ];
      }));

function make$1(param) {
  return Curry._2(make, param, compItems);
}

var ComponentSelect_000 = /* component */include[0];

var ComponentSelect = /* module */[
  ComponentSelect_000,
  /* compItems */compItems,
  /* make */make$1
];

var include$1 = Select$ReasonreactExamples.Make(/* module */[]);

var make$2 = include$1[1];

var moodItems = Belt_Array.map(/* array */[
      /* sad */5740566,
      /* shocked */-293737407,
      /* happy */572482848,
      /* blissful */-281233442,
      /* lovestruck */-326580162,
      /* excited */691427738,
      /* ko */23972
    ], (function (mood) {
        return /* record */[
                /* label */Kawaii$ReasonreactExamples.moodToJs(mood),
                /* value */mood
              ];
      }));

function make$3(param) {
  return Curry._2(make$2, param, moodItems);
}

var MoodSelect_000 = /* component */include$1[0];

var MoodSelect = /* module */[
  MoodSelect_000,
  /* moodItems */moodItems,
  /* make */make$3
];

var component = Curry._1(Prelude$ReasonreactExamples.RR[/* reducerComponent */2], "KawaiiDemo-ReasonreactExamples");

function make$4(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              return React.createElement("div", {
                          className: "KawaiiDemo"
                        }, React.createElement("h1", {
                              className: "mb-4"
                            }, Prelude$ReasonreactExamples.s("React-Kawaii Demo")), React.createElement("div", {
                              className: "mb-4"
                            }, React.createElement("span", {
                                  className: "mr-1"
                                }, Prelude$ReasonreactExamples.s("Mood:")), ReasonReact.element(undefined, undefined, Curry._5(make, /* Ghost */646315823, compItems, "mr-4", (function (v) {
                                        return Curry._1(send, /* ChangeComponent */Block.__(0, [v]));
                                      }), /* array */[])), React.createElement("span", {
                                  className: "mr-1"
                                }, Prelude$ReasonreactExamples.s("Mood:")), ReasonReact.element(undefined, undefined, Curry._5(make$2, /* happy */572482848, moodItems, undefined, (function (v) {
                                        return Curry._1(send, /* ChangeMood */Block.__(1, [v]));
                                      }), /* array */[]))), ReasonReact.element(undefined, undefined, Kawaii$ReasonreactExamples.SpeechBubble[/* make */0](param[/* state */1][/* mood */1], undefined, undefined, /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* component : Ghost */646315823,
                      /* mood : happy */572482848
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* component */state[/* component */0],
                            /* mood */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* component */action[0],
                            /* mood */state[/* mood */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  compChoiceToJs ,
  compChoiceFromJs ,
  ComponentSelect ,
  MoodSelect ,
  component ,
  make$4 as make,
  
}
/* include Not a pure module */
