// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Prelude$ReasonreactExamples from "../Prelude.bs.js";
import * as ValueBox$ReasonreactExamples from "../components/ValueBox.bs.js";

var component = Curry._1(Prelude$ReasonreactExamples.RR[/* statelessComponent */0], "Scratch-ReasonreactExamples");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "Scratch"
                        }, React.createElement("h1", {
                              className: "mb-4"
                            }, Prelude$ReasonreactExamples.s("Scratch")), React.createElement("h2", {
                              className: "mb-4"
                            }, Prelude$ReasonreactExamples.s("ValueBox")), ReasonReact.element(undefined, undefined, ValueBox$ReasonreactExamples.make("int", 677, /* array */[])), ReasonReact.element(undefined, undefined, ValueBox$ReasonreactExamples.make("float", 123.567, /* array */[])), ReasonReact.element(undefined, undefined, ValueBox$ReasonreactExamples.make("array", /* array */[
                                  1,
                                  2,
                                  3
                                ], /* array */[])), ReasonReact.element(undefined, undefined, ValueBox$ReasonreactExamples.make("list", /* :: */[
                                  1,
                                  /* :: */[
                                    2,
                                    /* :: */[
                                      3,
                                      /* [] */0
                                    ]
                                  ]
                                ], /* array */[])), ReasonReact.element(undefined, undefined, ValueBox$ReasonreactExamples.make("object", {
                                  apple: 1,
                                  banana: 2
                                }, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
