// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Random from "bs-platform/lib/es6/random.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as RR$ReasonreactExamples from "../RR.bs.js";
import * as Button$ReasonreactExamples from "../widgets/Button.bs.js";

var colors = [
  "blue",
  "red",
  "green",
  "purple",
  "yellow",
  "orange",
  "indigo"
];

function knuthShuffle(a) {
  var n = a.length;
  var a$1 = a.slice(0);
  for(var i = n - 1 | 0; i >= 1; --i){
    var k = Random.$$int(i + 1 | 0);
    var x = Belt_Array.getExn(a$1, k);
    Belt_Array.setExn(a$1, k, Belt_Array.getExn(a$1, i));
    Belt_Array.setExn(a$1, i, x);
  }
  return a$1;
}

function randomInt(min, max) {
  return Random.$$int((max - min | 0) + 1 | 0) + min | 0;
}

function getCharFromRange(min, max) {
  return String.fromCodePoint(randomInt(min, max));
}

function getRandomHanzi(n) {
  return Belt_Array.makeBy(n, (function (param) {
                return String.fromCodePoint(randomInt(19968, 40959));
              }));
}

function randomStyle(param) {
  var size = Random.$$int(4) + 1 | 0;
  return {
          fontSize: String(size) + "rem"
        };
}

function HelloWorld$RandomHanzi(Props) {
  var match = RR$ReasonreactExamples.useStateValue(getRandomHanzi(5));
  var setChars = match[1];
  var colors$1 = knuthShuffle(colors);
  return React.createElement("div", undefined, React.createElement(Button$ReasonreactExamples.make, {
                  onClick: (function (param) {
                      return Curry._1(setChars, getRandomHanzi(5));
                    }),
                  children: RR$ReasonreactExamples.s("Refresh")
                }), React.createElement("div", undefined, Belt_Array.map(Belt_Array.zip(match[0], colors$1), (function (param) {
                        var ch = param[0];
                        return React.createElement("span", {
                                    key: ch,
                                    className: "text-" + (param[1] + "-500"),
                                    style: randomStyle(undefined)
                                  }, RR$ReasonreactExamples.s(ch));
                      }))));
}

var RandomHanzi = {
  randomInt: randomInt,
  getCharFromRange: getCharFromRange,
  getRandomHanzi: getRandomHanzi,
  randomStyle: randomStyle,
  make: HelloWorld$RandomHanzi
};

function render(param) {
  return React.createElement("div", undefined, RR$ReasonreactExamples.s("你好世界！"), React.createElement(HelloWorld$RandomHanzi, {}));
}

var title = "Hello World";

export {
  title ,
  colors ,
  knuthShuffle ,
  RandomHanzi ,
  render ,
  
}
/* react Not a pure module */
