// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Prelude$ReasonreactExamples from "../Prelude.bs.js";

var component = Curry._1(Prelude$ReasonreactExamples.RR.statelessComponent, "Button-ReasonreactExamples");

function make(classNameOpt, text, onClick, _children) {
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var className$1 = Cn.make({
        hd: "text-grey-darker bg-grey-light px-2 py-1 rounded",
        tl: {
          hd: className,
          tl: /* [] */0
        }
      });
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (_self) {
              return React.createElement("button", {
                          className: className$1,
                          onClick: onClick
                        }, Prelude$ReasonreactExamples.s(text));
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
