// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as RR$ReasonreactExamples from "./RR.bs.js";
import * as Title$ReasonreactExamples from "./widgets/Title.bs.js";
import * as HelloWorld$ReasonreactExamples from "./examples/HelloWorld.bs.js";

function getSlug(title) {
  return title.toLowerCase().replace(/_/g, "-");
}

function home_render(param) {
  return RR$ReasonreactExamples.s("Use the navigation menu to select an example");
}

var home = {
  title: "Home",
  slug: "home",
  render: home_render
};

var modules_0 = {
  title: HelloWorld$ReasonreactExamples.title,
  render: HelloWorld$ReasonreactExamples.render
};

var modules = {
  hd: modules_0,
  tl: /* [] */0
};

var examplesFromModules = Belt_List.map(modules, (function (example) {
        return {
                title: example.title,
                slug: getSlug(example.title),
                render: example.render
              };
      }));

var examples = {
  hd: home,
  tl: examplesFromModules
};

function App(Props) {
  var match = RR$ReasonreactExamples.useStateValue(home);
  var setExample = match[1];
  var example = match[0];
  return React.createElement("div", {
              className: "h-screen flex flex-row"
            }, React.createElement("div", {
                  className: "bg-blue-600 text-white py-4 px-6 mr-8"
                }, React.createElement("div", {
                      className: "text-lg underline mb-4"
                    }, RR$ReasonreactExamples.s("Navigation")), RR$ReasonreactExamples.list(Belt_List.mapWithIndex(examples, (function (i, example) {
                            return React.createElement("div", {
                                        key: String(i),
                                        className: "cursor-pointer",
                                        onClick: (function (param) {
                                            return Curry._1(setExample, example);
                                          })
                                      }, RR$ReasonreactExamples.s(example.title));
                          })))), React.createElement("div", {
                  className: "mt-4 grid gap-4",
                  style: {
                    gridTemplateRows: "auto 1fr"
                  }
                }, React.createElement(Title$ReasonreactExamples.make, {
                      children: RR$ReasonreactExamples.s(example.title)
                    }), Curry._1(example.render, undefined)));
}

var make = App;

export {
  getSlug ,
  home ,
  examples ,
  make ,
  
}
/* examplesFromModules Not a pure module */
