// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Random from "bs-platform/lib/es6/random.js";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$ReasonreactExamples from "./App.bs.js";

Random.self_init(undefined);

ReactDOMRe.renderToElementWithId(React.createElement(App$ReasonreactExamples.make, {}), "index");

(((module.hot) ? module.hot.accept() : null));

export {
  
}
/*  Not a pure module */
