// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Random from "bs-platform/lib/es6/random.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$ReasonreactExamples from "./App.bs.js";

((require('./Index.pcss')));

Random.self_init(/* () */0);

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReasonreactExamples.make(/* array */[])), "index");

(((module.hot) ? module.hot.accept() : null));

export {
  
}
/*  Not a pure module */
