// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE

import * as Belt from "bs-platform/lib/es6/belt.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var RR = /* module */[
  /* statelessComponent */ReasonReact.statelessComponent,
  /* statelessComponentWithRetainedProps */ReasonReact.statelessComponentWithRetainedProps,
  /* reducerComponent */ReasonReact.reducerComponent,
  /* reducerComponentWithRetainedProps */ReasonReact.reducerComponentWithRetainedProps,
  /* element */ReasonReact.element,
  /* wrapReasonForJs */ReasonReact.wrapReasonForJs,
  /* createDomElement */ReasonReact.createDomElement,
  /* wrapJsForReason */ReasonReact.wrapJsForReason,
  /* Router */ReasonReact.Router
];

function s(prim) {
  return prim;
}

var Id = Belt.Id;

var $$Array = Belt.$$Array;

var SortArray = Belt.SortArray;

var MutableQueue = Belt.MutableQueue;

var MutableStack = Belt.MutableStack;

var List = Belt.List;

var Range = Belt.Range;

var $$Set = Belt.$$Set;

var $$Map = Belt.$$Map;

var MutableSet = Belt.MutableSet;

var MutableMap = Belt.MutableMap;

var HashSet = Belt.HashSet;

var HashMap = Belt.HashMap;

var Option = Belt.Option;

var Result = Belt.Result;

var Debug = Belt.Debug;

export {
  Id ,
  $$Array ,
  SortArray ,
  MutableQueue ,
  MutableStack ,
  List ,
  Range ,
  $$Set ,
  $$Map ,
  MutableSet ,
  MutableMap ,
  HashSet ,
  HashMap ,
  Option ,
  Result ,
  Debug ,
  RR ,
  s ,
  
}
/* ReasonReact Not a pure module */
