// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "reason-react/src/React.bs.js";
import * as React$1 from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

function s(prim) {
  return prim;
}

var list = Belt_List.toArray;

function useStateValue(initial) {
  return React$1.useReducer((function (_ignored, newState) {
                return newState;
              }), initial);
}

var Ref = React.Ref;

var Children = React.Children;

var Context = React.Context;

var Fragment = React.Fragment;

var StrictMode = React.StrictMode;

var Suspense = React.Suspense;

var SuspenseList = React.SuspenseList;

var Uncurried = React.Uncurried;

export {
  Ref ,
  Children ,
  Context ,
  Fragment ,
  StrictMode ,
  Suspense ,
  SuspenseList ,
  Uncurried ,
  s ,
  list ,
  useStateValue ,
  
}
/* react Not a pure module */
