// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Title(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-4xl"
            }, children);
}

var make = Title;

export {
  make ,
  
}
/* react Not a pure module */
